import UIKit

var greeting = "Hello, playground"

var newGame = gameStructu()
newGame.printGame()
newGame.move(row: 0, player: 1)
print("-----------")
newGame.printGame()
newGame.move(row: 0, player: 1)
print("-----------")
newGame.printGame()
newGame.move(row: 0, player: 1)
print("-----------")
newGame.printGame()
newGame.move(row: 0, player: 1)
print("-----------")
newGame.printGame()
newGame.move(row: 0, player: 1)
print("-----------")
newGame.printGame()
newGame.move(row: 0, player: 1)
print("-----------")
newGame.printGame()
newGame.move(row: 0, player: 1)
print("-----------")
newGame.printGame()
newGame.move(row: 0, player: 1)
print("-----------")
newGame.printGame()
newGame.move(row: 0, player: 1)
print("-----------")
newGame.printGame()
